### Color sources ###
# - CR neko white hero
# - Char design booklets
# adjusted

black  = '#040203'
dark   = '#090508'
somber = '#2e202a' #352832
dim    = '#575460'
soft   = '#e3e2e3'
light  = '#f9fafe'
white  = '#fffdfe'

[ansi.standard]
black   = '#232329'
red     = '#bf6a73'
green   = '#768b65'
yellow  = '#dabb5a'
blue    = '#6396cc'
magenta = '#8681ad'
cyan    = '#deaabb'
white   = '#e3e2e3'

[ansi.bright]
black   = '#3b3844' #5c5866
red     = '#bb4045' #c94f5b
green   = '#9dc1a1'
yellow  = '#f7ef9f' #f4e9aa
blue    = '#b8d6e6'
magenta = '#b48dbb'
cyan    = '#e5cae0'
white   = '#f5f3f5'

